name: PHA Resolve Diagnostic API
version: "0.1.0"
slug: pha_diagnostics
description: "Test add-on detection"
arch:
  - aarch64
  - amd64
  - armv7

startup: application
boot: auto

init: false
legacy: false
ingress: true
ingress_port: 8099
panel_icon: mdi:tools
panel_title: "Diagnostics"
