name: PHA Diagnostics API
version: "0.1.0"
slug: pha_diagnostics
description: "Test add-on detection"
arch:
  - aarch64
  - amd64
  - armv7

startup: application
boot: auto

init: false
legacy: false
ingress: false

ports:
  8000/tcp: 8000
