name: PHA Guardian Diagnostic API
version: "0.1.12"
slug: pha_diagnostics
description: "Test add-on detection"
arch:
  - aarch64
  - amd64
  - armv7

startup: application
boot: auto

init: false
legacy: false

ingress: true
ingress_port: 8000

panel_icon: mdi:tools
panel_title: "Diagnostics"

map:
  - supervisor_token:rw

options: {}
schema: {}
